import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../../public/css/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Video Conference',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' h-screen antialiased'}>
        {children}
      </body>
    </html>
  )
}
